--------------------------------------------------------
--  Constraints for Table PESSOA
--------------------------------------------------------

  ALTER TABLE "TESTE"."PESSOA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "TESTE"."PESSOA" MODIFY ("NIF" NOT NULL ENABLE);
  ALTER TABLE "TESTE"."PESSOA" ADD CONSTRAINT "PESSOA_PK" PRIMARY KEY ("NIF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
