--------------------------------------------------------
--  Constraints for Table QUARTO
--------------------------------------------------------

  ALTER TABLE "TESTE"."QUARTO" MODIFY ("LOCALIZACAO" NOT NULL ENABLE);
  ALTER TABLE "TESTE"."QUARTO" MODIFY ("IDQUARTO" NOT NULL ENABLE);
  ALTER TABLE "TESTE"."QUARTO" MODIFY ("OCUPACAO" NOT NULL ENABLE);
  ALTER TABLE "TESTE"."QUARTO" ADD CONSTRAINT "QUARTO_PK" PRIMARY KEY ("IDQUARTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
