--------------------------------------------------------
--  DDL for Table QUARTO
--------------------------------------------------------

  CREATE TABLE "TESTE"."QUARTO" 
   (	"LOCALIZACAO" VARCHAR2(100 BYTE), 
	"IDQUARTO" NUMBER(2,0), 
	"OCUPACAO" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "TESTE"."QUARTO"."LOCALIZACAO" IS 'CIDADE, RUA, NÚMERO, ANDAR E LADO';
   COMMENT ON COLUMN "TESTE"."QUARTO"."IDQUARTO" IS 'NÚMERO DO QUARTO NA CASO OU APARTAMENTO
';
   COMMENT ON COLUMN "TESTE"."QUARTO"."OCUPACAO" IS 'SIM OU NAO
';
